services:
  kafkarunner:
    image: python:3.6-slim
    restart: always
    ports:
    - "5000:5000"
    environment:
      ENVNAME: ${cucc}
      KAFKAUSER: ${KAFKAUSER}
      KAFKAPASS: ${KAFKAPASS}
    script:
      - docker build . -f build/kafka_runners/Dockerfile -t $IMAGE_KAFKA_RUNNER_SERVICE --cache-from=$IMAGE_KAFKA_RUNNER_SERVICE  
    entrypoint:
        /usr/lib/python3 in_topic_name="${INTOPICNAME}" out_topic_name="${OUTTOPICNAME}" bootstrap_servers="$BOOTSTRAPSERVERS"  
#    volumes:
#      - /media/storage0:/data
#      - ./certs:/certs
#      - ./auth:/auth
#    networks:
#      - mynet


#Docker Networks
#networks:
#  mynet:
#    driver: bridge

#Volumes
#volumes:
#  myregistrydata:
#    driver: local
# teszteléshez: python kafka_test_producer.py -m {\"jobId\":0\,\"timestamp\":0\,\"scenePath\":\"minio.python.api.test/test.blend\"\,\"outputLocation\":\"minio.python.api.test/render_test\"\,\"startFrame\":111\,\"numFrames\":2} render.job 10.8.8.226:9092


#FROM python:3.6-slim as staging
#RUN apt update && apt install -y git
#WORKDIR /app/
#RUN python -m venv /app/venv
## Enable venv
#ENV PATH="/app/venv/bin:$PATH"
#RUN git clone https://github.com/karolyartur/json_schemas
#COPY . /app/kafka_runners
#RUN pip install -Ur kafka_runners/requirements.txt

#FROM nytimes/blender:3.1-gpu-ubuntu18.04 as runner
#WORKDIR /app/
#COPY --from=staging /app /app
# Enable venv
#ENV PATH="/app/venv/bin:$PATH"
#RUN apt-get update && apt-get install -y python3 && update-alternatives --install /app/venv/bin/python3 python3 /usr/bin/python3 2
#CMD cd kafka_runners && python3 kafka_render.py $IN_KAFKA_TOPIC $OUT_KAFKA_TOPIC $KAFKA_BROKERS
